### ISSUE TITLE
How to activate plugin

### ISSUE THREAD

**Issue by cldwalker** [gerred/linter-kondo#1]
Hi. I'm looking to try this plugin. Currently when I try any of the standard linter commands on a clojure file I don't see any lint notices. Standard commands I've tried are linter:toggle-active-editor, linter:lint and linter:enable-linter. I've checked the notifications log and dev tools and don't see any errors. More on my environment:

Atom: 1.41.0-beta1
osx: 10.13.1
linter: 2.3.1
linter-kondo: 1.1.1
clj-kondo: v2019.08.21-alpha (installed via brew)

Any help appreciated. Cheers

**Comment by gerred** [comment]
Hi Gabriel!

I'm out and about and then I will look into this. Thank you!

**Comment by cldwalker** [comment]
Hi! I uncovered two issues that got me to a working state:
- I had installed clj-kondo while atom was open. Atom didn't detect clj-kondo on $PATH until I restarted atom
- After restarting atom, I was prompted to install the packages busy-signal, intentions and linter-ui-default and so I installed them. When I originally installed this package I was only prompted to install linter

Now it works great. Thanks for the package!

**Comment by gerred** [comment]
Ah ha! I will update the docs to match this and add the right dependencies,
unless you would like to PR it. :)

**Comment by cldwalker** [comment]
Any doc clarification on clj-kondo and $PATH would be great. Your package's dependencies are correct as are their dependencies. The bug seems to be with atom not prompting me to install all necessary dependencies at install time, leaving me in a broken state. I've had atom correctly install for 2 levels of dependencies. Perhaps it borked this time because it was 3 or 4 levels of dependencies
